#install.packages(c("devtools", "roxygen2", "usethis", "spelling"))
library(devtools)
library(roxygen2)
library(usethis)
library(spelling)

#options(usethis.full_name = "Combiz Khozoie")
#use_git()
#use_github()
use_mit_license()
use_readme_rmd()
use_travis()
use_testthat()
use_spell_check()
use_news_md()
